apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent
  namespace: argocd
spec:
  project: eventing
  source:
    repoURL: https://github.com/craigedmunds/argocd-eda.git
    path: kustomize/confluent
    
  destination:
    server: https://kubernetes.default.svc
    namespace: confluent
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
