apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    repo: argocd-eda
    component: cert-manager
spec:
  project: sdlc
  source:
    repoURL: oci://quay.io/jetstack/charts/cert-manager
    targetRevision: v1.19.1
    chart: cert-manager
    helm:
      parameters:
        - name: crds.enabled
          value: 'true'
      values: |
        # Configure cert-manager to use external DNS servers for SOA record resolution
        podDnsPolicy: "None"
        podDnsConfig:
          nameservers:
            - "8.8.8.8"
            - "1.1.1.1"
          searches:
            - "ctoaas.co"
          options:
            - name: ndots
              value: "2"
            - name: edns0

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        secrets/cloudflare-api-token: "true"
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true