apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
  namespace: argocd
  labels:
    repo: argocd-eda
    component: strimzi
    argocd-branch-targetrevision: "true"
spec:
  project: sdlc
  source:
    repoURL: https://github.com/craigedmunds/argocd-eda.git
    path: platform/kustomize/strimzi
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true