apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-kargo-admin-credentials
  annotations:
    policies.kyverno.io/title: Sync Kargo Admin Credentials
    policies.kyverno.io/category: Secret Management
    policies.kyverno.io/description: Creates Kargo admin credentials from central secret store
spec:
  admission: true
  background: true
  rules:
    - name: create-kargo-admin-credentials
      match:
        any:
          - resources:
              kinds:
                - Namespace
              names:
                - "*"
      preconditions:
        all:
          - key: "{{ request.object.metadata.labels.\"secrets/kargo-admin-credentials\" || '' }}"
            operator: Equals
            value: "true"
      context:
        - name: sourceSecret
          apiCall:
            urlPath: "/api/v1/namespaces/central-secret-store/secrets/kargo-admin-credentials"
            jmesPath: "data"
      generate:
        apiVersion: v1
        kind: Secret
        name: kargo-admin-credentials
        namespace: "{{ request.object.metadata.name }}"
        synchronize: true
        data:
          type: Opaque
          metadata:
            labels:
              managed-by: kyverno
              source: central-secret-store
              secret-type: kargo-admin-credentials
          data:
            ADMIN_ACCOUNT_PASSWORD_HASH: "{{ sourceSecret.\"ADMIN_ACCOUNT_PASSWORD_HASH\" }}"
            ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: "{{ sourceSecret.\"ADMIN_ACCOUNT_TOKEN_SIGNING_KEY\" }}"