apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-gh-git-credentials
  annotations:
    policies.kyverno.io/title: Sync GitHub Git Credentials
    policies.kyverno.io/category: Secret Management
    policies.kyverno.io/description: Creates GitHub Git credentials from GitHub PAT
spec:
  admission: true
  background: true
  rules:
    - name: create-github-git-credentials
      match:
        any:
          - resources:
              kinds:
                - Namespace
              names:
                - "*"
      preconditions:
        all:
          - key: "{{ request.object.metadata.labels.\"secrets/gh-git-credentials\" || '' }}"
            operator: Equals
            value: "true"
      context:
        - name: sourceSecret
          apiCall:
            urlPath: "/api/v1/namespaces/central-secret-store/secrets/github-pat"
            jmesPath: "data"
      generate:
        apiVersion: v1
        kind: Secret
        name: github-credentials
        namespace: "{{ request.object.metadata.name }}"
        synchronize: true
        data:
          type: Opaque
          metadata:
            labels:
              managed-by: kyverno
              source: central-secret-store
              secret-type: gh-git-credentials
          stringData:
            repoURL: "https://github.com/craigedmunds/argocd-eda.git"
            username: "{{ sourceSecret.username | base64_decode(@) }}"
            password: "{{ sourceSecret.token | base64_decode(@) }}"