apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: central-secret-store
spec:
  provider:
    kubernetes:
      # Use the current cluster
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: kube-system
      # Service account for accessing secrets in central-secret-store namespace
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets-system
      # Allow access to central-secret-store namespace
      remoteNamespace: central-secret-store