apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eda-mesh-lob-applications
spec:
  template:
    spec:
      source:
        helm:
          parameters:
            - name: name
              value: '{{.path.basename}}'
            # - name: feature_branch
            #   value: feature/backstage-events
