#!/usr/bin/env python3
"""
Tests for Kargo ingress build transformations.

Tests the platform/kustomize/seed/overlays/local/lab/ to ensure:
- Kargo ingress is generated by Helm chart with multi-path support
- Both / and /webhooks paths are configured correctly
- Public access pattern provides both internal and external domains
- TLS configuration covers both domains
"""
import pytest
from base_test import BaseIngressTest


@pytest.mark.ingress
@pytest.mark.kargo
class TestKargoIngressHelmGenerated(BaseIngressTest):
    """Test Kargo ingress (generated by Helm chart with multi-path support)."""
    
    @staticmethod
    def get_overlay_path() -> str:
        """Return the lab overlay path where Kargo ingress is generated."""
        return "../kustomize/seed/overlays/local/lab"
    
    def get_expected_ingress_name(self) -> str:
        """Return the Kargo ingress name."""
        return "kargo-ingress"
    
    def get_expected_hosts(self) -> list[str]:
        """Return the expected hosts for public access pattern."""
        return [
            "kargo.lab.local.ctoaas.co",  # Internal domain
            "kargo.lab.ctoaas.co"         # External domain
        ]
    
    def test_has_public_access_pattern(self, kustomize_builder, ingress_validator):
        """Test that Kargo ingress has both internal and external domains (public access)."""
        ingress = self.get_ingress_resource(kustomize_builder, ingress_validator)
        actual_hosts = ingress_validator.get_hosts(ingress)
        expected_hosts = self.get_expected_hosts()
        
        assert set(actual_hosts) == set(expected_hosts), \
            f"Kargo ingress should have both internal and external domains. Expected: {expected_hosts}, Got: {actual_hosts}"
    
    def test_has_multi_path_configuration(self, kustomize_builder, ingress_validator):
        """Test that Kargo ingress has both / and /webhooks paths."""
        ingress = self.get_ingress_resource(kustomize_builder, ingress_validator)
        rules = ingress.get("spec", {}).get("rules", [])
        
        # Should have rules for both domains
        assert len(rules) == 2, f"Kargo ingress should have 2 rules (internal + external), got {len(rules)}"
        
        # Check that both rules have both paths
        for rule in rules:
            host = rule.get("host")
            paths = rule.get("http", {}).get("paths", [])
            
            assert len(paths) == 2, f"Each rule should have 2 paths (/ and /webhooks), got {len(paths)} for host {host}"
            
            # Extract path values
            path_values = [path.get("path") for path in paths]
            assert "/" in path_values, f"Rule for {host} should have / path"
            assert "/webhooks" in path_values, f"Rule for {host} should have /webhooks path"
    
    def test_has_correct_service_backends(self, kustomize_builder, ingress_validator):
        """Test that paths point to the correct services."""
        ingress = self.get_ingress_resource(kustomize_builder, ingress_validator)
        rules = ingress.get("spec", {}).get("rules", [])
        
        for rule in rules:
            host = rule.get("host")
            paths = rule.get("http", {}).get("paths", [])
            
            for path in paths:
                path_value = path.get("path")
                service_name = path.get("backend", {}).get("service", {}).get("name")
                
                if path_value == "/":
                    assert service_name == "kargo-api", \
                        f"Root path (/) should point to 'kargo-api', got '{service_name}' for host {host}"
                elif path_value == "/webhooks":
                    assert service_name == "kargo-external-webhooks-server", \
                        f"Webhooks path should point to 'kargo-external-webhooks-server', got '{service_name}' for host {host}"
    
    def test_has_correct_service_ports(self, kustomize_builder, ingress_validator):
        """Test that services use correct port numbers."""
        ingress = self.get_ingress_resource(kustomize_builder, ingress_validator)
        rules = ingress.get("spec", {}).get("rules", [])
        
        for rule in rules:
            paths = rule.get("http", {}).get("paths", [])
            
            for path in paths:
                port_config = path.get("backend", {}).get("service", {}).get("port", {})
                port_number = port_config.get("number")
                
                # Both services should use port 80
                assert port_number == 80, \
                    f"Service port should be 80, got {port_number} for path {path.get('path')}"
    
    def test_has_tls_configuration(self, kustomize_builder, ingress_validator):
        """Test that Kargo ingress has TLS configuration for both domains."""
        ingress = self.get_ingress_resource(kustomize_builder, ingress_validator)
        tls_configs = ingress.get("spec", {}).get("tls", [])
        
        assert len(tls_configs) == 1, "Kargo ingress should have exactly one TLS configuration"
        
        # Get all TLS hosts
        tls_hosts = ingress_validator.get_tls_hosts(ingress)
        expected_hosts = self.get_expected_hosts()
        
        # TLS should cover both domains
        assert set(tls_hosts) == set(expected_hosts), \
            f"TLS should cover both domains. Expected: {expected_hosts}, Got: {tls_hosts}"
    
    def test_tls_secret_name_generation(self, kustomize_builder, ingress_validator):
        """Test that TLS secret name is generated correctly."""
        ingress = self.get_ingress_resource(kustomize_builder, ingress_validator)
        tls_configs = ingress.get("spec", {}).get("tls", [])
        
        assert len(tls_configs) == 1, "Kargo ingress should have exactly one TLS configuration"
        
        tls_config = tls_configs[0]
        secret_name = tls_config.get("secretName")
        
        # Secret name should be the configured one from Helm chart
        expected_secret_name = "kargo-ctoaas-tls"
        assert secret_name == expected_secret_name, \
            f"TLS secret name should be '{expected_secret_name}', got '{secret_name}'"
    
    def test_namespace_is_kargo(self, kustomize_builder, ingress_validator):
        """Test that Kargo ingress is in the kargo namespace."""
        ingress = self.get_ingress_resource(kustomize_builder, ingress_validator)
        namespace = ingress.get("metadata", {}).get("namespace")
        
        assert namespace == "kargo", \
            f"Kargo ingress should be in 'kargo' namespace, got '{namespace}'"
    
    def test_has_traefik_ingress_class(self, kustomize_builder, ingress_validator):
        """Test that Kargo ingress has traefik ingress class."""
        ingress = self.get_ingress_resource(kustomize_builder, ingress_validator)
        ingress_class = ingress.get("spec", {}).get("ingressClassName")
        
        assert ingress_class == "traefik", \
            f"Kargo ingress should have ingressClassName 'traefik', got '{ingress_class}'"
    
    def test_has_traefik_annotations(self, kustomize_builder, ingress_validator):
        """Test that Kargo ingress has required Traefik annotations."""
        ingress = self.get_ingress_resource(kustomize_builder, ingress_validator)
        annotations = ingress_validator.get_annotations(ingress)
        
        # Should have Traefik router annotations
        assert "traefik.ingress.kubernetes.io/router.entrypoints" in annotations, \
            "Kargo ingress should have Traefik router.entrypoints annotation"
        assert annotations["traefik.ingress.kubernetes.io/router.entrypoints"] == "websecure", \
            f"Traefik entrypoints should be 'websecure', got '{annotations.get('traefik.ingress.kubernetes.io/router.entrypoints')}'"
        
        assert "traefik.ingress.kubernetes.io/router.tls" in annotations, \
            "Kargo ingress should have Traefik router.tls annotation"
        assert annotations["traefik.ingress.kubernetes.io/router.tls"] == "true", \
            f"Traefik TLS should be 'true', got '{annotations.get('traefik.ingress.kubernetes.io/router.tls')}'"
    
    def test_has_cert_manager_annotations(self, kustomize_builder, ingress_validator):
        """Test that Kargo ingress has cert-manager annotations."""
        ingress = self.get_ingress_resource(kustomize_builder, ingress_validator)
        annotations = ingress_validator.get_annotations(ingress)
        
        # Should have cert-manager cluster issuer annotation
        assert "cert-manager.io/cluster-issuer" in annotations, \
            "Kargo ingress should have cert-manager cluster-issuer annotation"
        assert annotations["cert-manager.io/cluster-issuer"] == "letsencrypt-prod", \
            f"cert-manager issuer should be 'letsencrypt-prod', got '{annotations.get('cert-manager.io/cluster-issuer')}'"


@pytest.mark.ingress
@pytest.mark.integration
class TestKargoIngressIntegration:
    """Integration tests for Kargo ingress (Helm-generated)."""
    
    def test_kargo_ingress_generated_in_lab_overlay(self, kustomize_builder, ingress_validator):
        """Test that Kargo ingress is properly generated by Helm chart in lab overlay."""
        # Build the lab overlay which includes Kargo Helm chart
        lab_documents = kustomize_builder("../kustomize/seed/overlays/local/lab")
        
        # Find Kargo ingress in the lab build
        kargo_ingress = ingress_validator.find_ingress_by_name(lab_documents, "kargo-ingress")
        
        assert kargo_ingress is not None, "Kargo ingress should be generated by Helm chart in lab overlay"
        
        # Validate multi-path configuration
        rules = kargo_ingress.get("spec", {}).get("rules", [])
        assert len(rules) == 2, "Kargo ingress should have rules for both internal and external domains"
        
        # Validate that both rules have both paths
        for rule in rules:
            paths = rule.get("http", {}).get("paths", [])
            assert len(paths) == 2, "Each rule should have both / and /webhooks paths"
            
            path_values = [path.get("path") for path in paths]
            assert "/" in path_values and "/webhooks" in path_values, \
                "Each rule should have both / and /webhooks paths"
        
        # Validate TLS covers both domains
        tls_hosts = ingress_validator.get_tls_hosts(kargo_ingress)
        expected_hosts = ["kargo.lab.local.ctoaas.co", "kargo.lab.ctoaas.co"]
        assert set(tls_hosts) == set(expected_hosts), \
            f"TLS should cover both domains. Expected: {expected_hosts}, Got: {tls_hosts}"