repository:
  name: "argocd-eda"
  type: "mono-repo"
  description: "Event-driven architecture platform with developer tooling and container lifecycle management"
  
capabilities:
  - name: "backstage"
    type: "capability"
    path: "backstage"
    infrastructure: "backstage/kustomize"
    description: "Internal developer catalog and portal"
    production: true
    components:
      - "backstage-app"
      - "backstage-kargo"
    
  - name: "image-factory"
    type: "capability"
    path: "image-factory"
    infrastructure: "image-factory/cdk8s"
    description: "Container lifecycle management system"
    production: true
    components:
      - "image-factory"
    
  - name: "eda"
    type: "capability"
    path: "eda"
    infrastructure: "eda/kustomize"
    description: "Event-driven architecture platform"
    production: true
    components:
      - "eda-mesh"
      - "camel-karavan"

supporting_apps:
  - name: "e2e-test-runner"
    path: "apps/e2e-test-runner"
    description: "End-to-end testing utilities"
    production: false
    
  - name: "uv"
    path: "apps/uv"
    description: "UV service application"
    production: false

platform_infrastructure:
  - name: "argocd"
    path: "platform/kustomize/seed/argocd"
    description: "GitOps deployment engine"
    required: true
    
  - name: "kargo"
    path: "platform/kustomize/kargo"
    description: "GitOps promotion engine"
    production: false
    
  - name: "central-secret-store"
    path: "platform/kustomize/central-secret-store"
    description: "Centralized secret management"
    production: false
    
  - name: "kyverno"
    description: "Policy engine for Kubernetes"
    production: false
    
  - name: "cert-manager"
    description: "Certificate management"
    production: false

bootstrap:
  seed_path: "platform/kustomize/seed"
  environments:
    local:
      pi:
        command: "kubectl apply -k platform/kustomize/seed/overlays/local/pi/"
        description: "Full capability set for Pi environment"
        includes:
          - argocd
          - backstage
          - image-factory
          - eda
          - supporting-applications
          
      craig:
        command: "kubectl apply -k platform/kustomize/seed/overlays/local/craig/"
        description: "Reduced capability set without Image Factory"
        includes:
          - argocd
          - backstage
          - eda
          - supporting-applications
          
      niv:
        command: "kubectl apply -k platform/kustomize/seed/overlays/local/niv/"
        description: "Full capability set for Niv environment"
        includes:
          - argocd
          - backstage
          - image-factory
          - eda
          - supporting-applications
          
    production:
      command: "kubectl apply -k platform/kustomize/seed/overlays/production/"
      description: "Core capabilities only for production"
      includes:
        - argocd
        - backstage
        - image-factory
        - eda

migration:
  status: "completed"
  consolidated_from:
    - "seed/"
    - "kustomize/seed/"
  consolidated_to: "platform/kustomize/seed/"
  deprecated_paths:
    - "seed/"
    - "kustomize/_common/"
    - "kustomize/central-secret-store/"
    - "kustomize/kargo/"