version: '3'

tasks:
  test:unit:setup:
    desc: "Setup unit tests"
    dir: tests/unit
    cmds:
      - cmd: echo "🧪 Setting up unit tests..."
        silent: true
      - cmd: |
          if [ -n "$CI" ]; then
            pip install -r requirements.txt
          else
            .venv/bin/pip install -r requirements.txt
          fi

  test:unit:
    desc: "Run unit tests for branch targeting component"
    dir: tests/unit
    cmds:
      - cmd: echo "🧪 Running branch targeting unit tests..."
        silent: true
      - cmd: |
          if [ -n "$CI" ]; then
            python -m pytest -v --tb=short
          else
            .venv/bin/python -m pytest -v --tb=short
          fi
      - cmd: echo "✅ All branch targeting unit tests passed"
        silent: true

  test:all:
    desc: "Run all tests for branch targeting component"
    deps: [test:unit]