apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: code-server-ssh-key
  namespace: code-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: central-secret-store
  target:
    name: code-server-ssh-key
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          managed-by: external-secrets
          source: central-secret-store
          app: code-server
      data:
        id_rsa: "{{ .id_rsa }}"
        id_rsa.pub: "{{ .id_rsa_pub }}"
  data:
  - secretKey: id_rsa
    remoteRef:
      key: code-server-ssh-key
      property: id_rsa
  - secretKey: id_rsa_pub
    remoteRef:
      key: code-server-ssh-key
      property: id_rsa.pub