apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: analyze-dockerfile
  namespace: image-factory-kargo
spec:
  args:
    - name: imageName
    - name: imageTag
    - name: imageDigest
    - name: dockerfile
    - name: sourceRepo
    - name: sourceProvider
    - name: gitRepo
    - name: gitBranch
  metrics:
    - name: dockerfile-analysis
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                serviceAccountName: image-factory
                restartPolicy: Never
                imagePullSecrets:
                  - name: ghcr-pull-secret
                containers:
                  - name: analyzer
                    image: ghcr.io/craigedmunds/uv:latest
                    imagePullPolicy: Always
                    command:
                      - /bin/sh
                      - /scripts/run.sh
                      - app.py
                      - --image
                      - "{{args.imageName}}"
                      - --tag
                      - "{{args.imageTag}}"
                      - --digest
                      - "{{args.imageDigest}}"
                      - --dockerfile
                      - "{{args.dockerfile}}"
                      - --source-repo
                      - "{{args.sourceRepo}}"
                      - --source-provider
                      - "{{args.sourceProvider}}"
                      - --git-repo
                      - "{{args.gitRepo}}"
                      - --git-branch
                      - "{{args.gitBranch}}"
                    volumeMounts:
                      - name: analyzer-script
                        mountPath: /integration
                    env:
                      - name: GITHUB_TOKEN
                        valueFrom:
                          secretKeyRef:
                            name: ghcr-credentials
                            key: password
                volumes:
                  - name: analyzer-script
                    configMap:
                      name: image-factory-analysis
