apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: analyze-dockerfile
  namespace: image-factory-kargo
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: backstage
      sources:
        direct: true
  
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/craigedmunds/argocd-eda.git
            checkout:
              - branch: main
                path: ./repo
  
  verification:
    analysisTemplates:
      - name: analyze-dockerfile
    args:
      - name: imageName
        value: backstage
      - name: imageTag
        value: ${{ imageFrom("ghcr.io/craigedmunds/backstage").Tag }}
      - name: imageDigest
        value: ${{ imageFrom("ghcr.io/craigedmunds/backstage").Digest }}
      - name: dockerfile
        value: apps/backstage/packages/backend/Dockerfile
      - name: sourceRepo
        value: craigedmunds/argocd-eda
      - name: sourceProvider
        value: github
      - name: gitRepo
        value: https://github.com/craigedmunds/argocd-eda.git
      - name: gitBranch
        value: feature/backstage-events
