apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: analyzed
  namespace: image-factory-kargo
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: backstage
      sources:
        stages:
          - analyze-dockerfile
  
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/craigedmunds/argocd-eda.git
            checkout:
              - branch: main
                path: ./repo
