version: '3'

tasks:

  test:unit:
    desc: Run unit tests for an EDA app (mesh or core service)
    dir: '{{if eq .CATEGORY "services"}}services/{{.APP}}{{else}}mesh/{{.CATEGORY}}/{{.APP}}{{end}}'
    cmds:
      - test -d .venv || uv venv
      - uv sync --all-groups
      - .venv/bin/python -m pytest tests/
    vars:
      CATEGORY: '{{.CATEGORY | default "services"}}'
    requires:
      vars: [APP]

  logs:rabbitmq:
    desc: Follow RabbitMQ logs
    cmds:
      - kubectl logs -f eda-mesh-rabbitmq-server-0 -n eda-mesh

  passwords:rabbitmq:
    desc: Get RabbitMQ admin credentials
    cmds:
      - cmd: echo "RabbitMQ Username:"
        silent: true
      - kubectl get secret eda-mesh-rabbitmq-default-user -n eda-mesh -o jsonpath='{.data.username}' | base64 -d
      - cmd: echo -e "\nRabbitMQ Password:"
        silent: true
      - kubectl get secret eda-mesh-rabbitmq-default-user -n eda-mesh -o jsonpath='{.data.password}' | base64 -d
      - cmd: echo -e "\nRabbitMQ Management URL:"
        silent: true
      - cmd: echo "https://$(kubectl get ingress rabbitmq-ingress -n eda-mesh -o jsonpath='{.spec.rules[0].host}')/"
      
  ui:rabbitmq:
    desc: Open RabbitMQ Management UI in browser
    cmds:
      - cmd: echo "Opening RabbitMQ Management UI..."
        silent: true
      - cmd: |
          RABBITMQ_URL="https://$(kubectl get ingress rabbitmq-ingress -n eda-mesh -o jsonpath='{.spec.rules[0].host}')/"
          echo "URL - $RABBITMQ_URL"
          echo "Use task eda:passwords:rabbitmq to get credentials"
          open "$RABBITMQ_URL"

  status:
    desc: Show EDA mesh application and component status
    cmds:
      - cmd: echo "=== EDA Mesh Application Status ==="
        silent: true
      - kubectl get application eda-mesh -n argocd -o wide
      - cmd: echo -e "\n=== EDA Mesh Pods ==="
        silent: true
      - kubectl get pods -n eda-mesh
      - cmd: echo -e "\n=== RabbitMQ Cluster Status ==="
        silent: true
      - kubectl get rabbitmqcluster eda-mesh-rabbitmq -n eda-mesh
      - cmd: echo -e "\n=== RabbitMQ Services ==="
        silent: true
      - kubectl get services -n eda-mesh
      - cmd: echo -e "\n=== RabbitMQ Ingress ==="
        silent: true
      - kubectl get ingress -n eda-mesh

  build:
    desc: Build EDA mesh kustomize configuration
    dir: kustomize/mesh/overlays/lab
    cmds:
      - kustomize build --enable-helm --load-restrictor=LoadRestrictionsNone .
      
  apply:
    desc: Apply EDA mesh kustomize configuration
    dir: kustomize/mesh/overlays/lab
    cmds:
      - kubectl apply -k .
      - cmd: echo "Applied EDA mesh configuration"
        silent: true

  diff:
    desc: Show diff between local changes and cluster state
    dir: kustomize/mesh/overlays/lab
    cmds:
      - kubectl diff -k .


  demo:consumer:
    desc: Run Kafka console consumer
    vars:
      TOPIC: '{{.TOPIC | default "users"}}'
    cmds:
      - kubectl run demo-kafka-consumer -n kafka --image=quay.io/strimzi/kafka:0.49.1-kafka-4.1.1 --rm=true --restart=Never -ti -- bin/kafka-console-consumer.sh --bootstrap-server my-cluster-kafka-bootstrap:9092 --topic {{.TOPIC}} --from-beginning
