apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backstage-acceptance-verification
  namespace: backstage-kargo
spec:
  args:
    - name: backstage-url
      value: http://backstage.backstage.svc.cluster.local:7007
  
  metrics:
    # Run comprehensive acceptance tests using the Python script
    - name: acceptance-tests
      provider:
        job:
          spec:
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: e2e-runner
                    image: ghcr.io/craigedmunds/e2e-test-runner:0.1.4
                    command: ["/bin/bash"]
                    args:
                      - "-c"
                      - |
                        # Redirect all output to log file for Kargo UI
                        exec > >(tee /artifacts/verification.log) 2>&1
                        
                        # Setup Traefik host resolution
                        /scripts/setup_traefik_hosts.sh
                        
                        # Execute verification tests directly with Python script
                        python3 /scripts/post_deployment_e2e.py \
                          --url "{{args.backstage-url}}" \
                          --max-wait-time 300 \
                          --verbose
                        
                        # Capture exit code
                        EXIT_CODE=$?
                        
                        # Ensure log is flushed
                        sync
                        
                        exit $EXIT_CODE
                    env:
                      - name: BACKSTAGE_URL
                        value: "{{args.backstage-url}}"
                      - name: PLAYWRIGHT_BROWSERS_PATH
                        value: "/ms-playwright"
                      - name: KARGO_PROMOTION_ID
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: KARGO_FREIGHT_ID
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.labels['kargo.akuity.io/freight-collection']
                    volumeMounts:
                      - name: acceptance-scripts
                        mountPath: /scripts
                        readOnly: true
                      - name: acceptance-tests
                        mountPath: /workspace/backstage/app/tests/acceptance
                        readOnly: true
                      - name: acceptance-lib
                        mountPath: /workspace/backstage/app/tests/acceptance/lib
                        readOnly: true
                      - name: eda-plugin-tests
                        mountPath: /workspace/backstage/app/plugins/eda/tests/acceptance
                        readOnly: true
                      - name: image-factory-plugin-tests
                        mountPath: /workspace/backstage/app/plugins/image-factory/tests/acceptance
                        readOnly: true
                      - name: acceptance-artifacts
                        mountPath: /artifacts
                volumes:
                  - name: acceptance-scripts
                    configMap:
                      name: backstage-acceptance-scripts
                      defaultMode: 0755
                  - name: acceptance-tests
                    configMap:
                      name: backstage-acceptance-tests
                      defaultMode: 0755
                  - name: acceptance-lib
                    configMap:
                      name: backstage-acceptance-lib
                      defaultMode: 0755
                  - name: eda-plugin-tests
                    configMap:
                      name: backstage-eda-plugin-tests
                      defaultMode: 0755
                  - name: image-factory-plugin-tests
                    configMap:
                      name: backstage-image-factory-plugin-tests
                      defaultMode: 0755
                  - name: acceptance-artifacts
                    hostPath:
                      path: /var/lib/backstage-acceptance-artifacts
                      type: DirectoryOrCreate
      successCondition: "result.phase == Succeeded"
      failureCondition: "result.phase == Failed"
      failureLimit: 1
      interval: 60s
      count: 1