apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: backstage
  namespace: backstage-kargo
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/craigedmunds/backstage
        semverConstraint: ">=0.6.0"
        discoveryLimit: 10
    
    # This is a temporary measure that generates new freight each time the backstage-verification.yaml
    # changes so that the verification is forced to run
    - git:
        repoURL: https://github.com/craigedmunds/argocd-eda.git
        branch: main
        # Watch the verification template so changes force new freight
        includePaths:
          - backstage/kustomize/kargo
          # /backstage-verification.yaml
          # - backstage/kustomize/kargo/scripts/post_deployment_e2e.py
