apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: arc-github-token
  namespace: central-secret-store
spec:
  # Distribute GitHub PAT to arc-systems namespace
  namespaceSelector:
    matchLabels:
      secrets/arc-github-token: "true"
  
  refreshTime: "1h"
  
  externalSecretSpec:
    secretStoreRef:
      name: central-secret-store
      kind: ClusterSecretStore
    
    target:
      name: github-arc-secret
      creationPolicy: Owner
      template:
        type: Opaque
        data:
          # ARC expects the token in this field
          github_token: "{{ .github_token }}"
    
    data:
      - secretKey: github_token
        remoteRef:
          key: github-pat
          property: token
