apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: arc-systems
spec:
  interval: 1h
  url: https://actions.github.io/actions-runner-controller
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arc-controller
  namespace: arc-systems
spec:
  interval: 10m
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: "0.9.x"  # Use latest 0.9.x
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: arc-systems
  
  # Wait for namespace and secret to be ready
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  
  install:
    remediation:
      retries: 3
    createNamespace: false
  
  upgrade:
    remediation:
      retries: 3
  
  values:
    # Controller configuration
    replicaCount: 1
    
    # Resource limits for controller
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    
    # Use cert-manager for certificates
    certManager:
      enabled: true
    
    # Image configuration
    image:
      repository: ghcr.io/actions/gha-runner-scale-set-controller
      pullPolicy: IfNotPresent
