apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-runner
  namespace: arc-systems
imagePullSecrets:
  - name: gh-docker-registry-creds
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-runner
  namespace: arc-systems
rules:
  # Allow runners to read config maps and secrets
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
  
  # Allow runners to create/manage jobs (for nested job execution if needed)
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]
  
  # Allow runners to read pods (for debugging)
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runner
  namespace: arc-systems
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-runner
subjects:
  - kind: ServiceAccount
    name: arc-runner
    namespace: arc-systems
