apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backstage-health-check
  namespace: backstage
spec:
  metrics:
    - name: backstage-http-check
      interval: 30s
      successCondition: result == "200"
      failureLimit: 3
      provider:
        web:
          url: "https://backstage.{{ .stage }}.127.0.0.1.nip.io/healthcheck"
          timeoutSeconds: 10
          jsonPath: "{$.status}"
    - name: backstage-catalog-check
      interval: 30s
      successCondition: result > 0
      failureLimit: 3
      provider:
        web:
          url: "https://backstage.{{ .stage }}.127.0.0.1.nip.io/api/catalog/entities"
          timeoutSeconds: 10
          jsonPath: "{$.length}"
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backstage-smoke-tests
  namespace: backstage
spec:
  metrics:
    - name: backstage-api-response-time
      interval: 30s
      successCondition: result < 2000
      failureLimit: 3
      provider:
        web:
          url: "https://backstage.{{ .stage }}.127.0.0.1.nip.io/api/catalog/entities"
          timeoutSeconds: 10
          jsonPath: "{$.responseTime}"
