apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: backstage-project
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: backstage
      sources:
        stages:
          - staging
  
  verification:
    analysisTemplates:
      - name: backstage-health-check
  
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/craigedmunds/backstage-demo.git
            checkout:
              - branch: main
                path: ./repo
        
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./repo/kustomize/backstage/overlays/production
            images:
              - image: ghcr.io/craigedmunds/backstage
        
        - uses: git-commit
          as: commit
          config:
            path: ./repo
            messageFromSteps:
              - update-image
        
        - uses: git-push
          config:
            path: ./repo
            targetBranch: main
