apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: backstage-kargo
spec:
  # Subscribe to the warehouse for new images
  subscriptions:
    warehouse: backstage
  
  # Auto-promote to dev
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/craigedmunds/argocd-eda.git
        writeBranch: main
        kustomize:
          images:
            - image: ghcr.io/craigedmunds/backstage
              path: kustomize/backstage/overlays/dev
    
    argoCDAppUpdates:
      - appName: backstage-dev
        appNamespace: argocd
  
  # Verification - optional health checks
  verification:
    analysisTemplates:
      - name: backstage-health-check
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: backstage-kargo
spec:
  # Promote from dev
  subscriptions:
    upstreamStages:
      - name: dev
  
  # Manual approval required for staging
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/craigedmunds/argocd-eda.git
        writeBranch: main
        kustomize:
          images:
            - image: ghcr.io/craigedmunds/backstage
              path: kustomize/backstage/overlays/staging
    
    argoCDAppUpdates:
      - appName: backstage-staging
        appNamespace: argocd
  
  verification:
    analysisTemplates:
      - name: backstage-health-check
      - name: backstage-smoke-tests
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: backstage-kargo
spec:
  # Promote from staging
  subscriptions:
    upstreamStages:
      - name: staging
  
  # Manual approval + verification required for production
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/craigedmunds/argocd-eda.git
        writeBranch: main
        kustomize:
          images:
            - image: ghcr.io/craigedmunds/backstage
              path: kustomize/backstage/overlays/production
    
    argoCDAppUpdates:
      - appName: backstage-production
        appNamespace: argocd
  
  verification:
    analysisTemplates:
      - name: backstage-health-check
      - name: backstage-smoke-tests
      - name: backstage-load-tests
