apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: backstage
  namespace: backstage-kargo
spec:
  # Subscribe to new images from GitHub Container Registry
  subscriptions:
    - image:
        repoURL: ghcr.io/craigedmunds/backstage
        semverConstraint: ">=0.6.0"
        discoveryLimit: 10
        # Use GitHub token for private repos
        # imagePullSecrets:
        #   - name: ghcr-creds
