apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: sdlc
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.37.7
    chart: argo-rollouts
    helm:
      values: |
        dashboard:
          enabled: true
          ingress:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - argo-rollouts.127.0.0.1.nip.io
            pathType: Prefix
        
        # Configure log streaming for AnalysisRuns
        controller:
          component: rollouts-controller
          logLevel: info
        
        # Add ConfigMap data for log streaming
        configMap:
          create: true
          data:
            logLevel: info
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
