apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-factory
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/craigedmunds/argocd-eda.git
    path: cdk8s/image-factory/dist
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: image-factory
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
