apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: eventing
  source:
    repoURL: oci://ghcr.io/akuity/kargo-charts/kargo
    targetRevision: 1.8.4
    chart: kargo
    helm:
      parameters:
        - name: api.adminAccount.enabled
          value: "true"
        - name: api.adminAccount.passwordHash
          value: <path:argocd/kargo-admin-credentials#passwordHash>
        - name: api.adminAccount.tokenSigningKey
          value: <path:argocd/kargo-admin-credentials#tokenSigningKey>
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
