apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: eventing
  source:
    repoURL: oci://ghcr.io/akuity/kargo-charts/kargo
    targetRevision: 1.8.4
    chart: kargo
    helm:
      values: |
        api:
          host: kargo.127.0.0.1.nip.io
          secret:
            name: kargo-admin-credentials
          adminAccount:
            enabled: true
          tls:
            enabled: false
          ingress:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            pathType: Prefix
        
        extraObjects:
          - apiVersion: kyverno.io/v1
            kind: ClusterPolicy
            metadata:
              name: sync-ghcr-secret-to-kargo
              annotations:
                policies.kyverno.io/title: Sync GHCR Secret to Kargo Namespaces
                policies.kyverno.io/category: Sync
                policies.kyverno.io/subject: Secret
                policies.kyverno.io/minversion: 1.6.0
                policies.kyverno.io/description: Syncs the GHCR credentials secret to Kargo project namespaces in the format Kargo expects
            spec:
              rules:
              - name: sync-ghcr-secret
                match:
                  any:
                  - resources:
                      kinds:
                      - Namespace
                      selector:
                        matchLabels:
                          kargo.akuity.io/project: "true"
                          kargo.deps/ghcr: "true"
                context:
                - name: sourceSecret
                  apiCall:
                    urlPath: /api/v1/namespaces/backstage/secrets/ghcr-creds
                    jmesPath: data.".dockerconfigjson" | base64_decode(@) | parse_json(@).auths."ghcr.io"
                generate:
                  apiVersion: v1
                  kind: Secret
                  type: Opaque
                  name: ghcr-credentials
                  namespace: "{{`{{ request.object.metadata.name }}`}}"
                  synchronize: true
                  data:
                    metadata:
                      labels:
                        kargo.akuity.io/cred-type: image
                    stringData:
                      repoURL: ghcr.io/craigedmunds/backstage
                      username: "{{`{{ sourceSecret.username }}`}}"
                      password: "{{`{{ sourceSecret.password }}`}}"

  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
