apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verdaccio
  namespace: argocd
spec:
  project: eventing
  source:
    repoURL: https://charts.verdaccio.org
    chart: verdaccio
    targetRevision: 4.28.0
  destination:
    server: https://kubernetes.default.svc
    namespace: verdaccio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
