apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: enroll-managed-image
  title: Enroll Managed Image
  description: Register a container image for automated dependency tracking and rebuilds in the Image Factory system
  tags:
    - image-factory
    - container
    - docker
    - automation
spec:
  owner: platform-team
  type: image
  
  parameters:
    - title: Image Information
      required:
        - name
        - registry
        - repository
      properties:
        name:
          title: Image Name
          type: string
          description: Unique identifier for the image (lowercase, hyphens allowed)
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
          ui:help: 'Example: my-web-app, user-service, payment-api'
        registry:
          title: Container Registry
          type: string
          description: Registry where the image is stored
          default: ghcr.io
          enum:
            - ghcr.io
            - docker.io
            - registry.example.com
          enumNames:
            - 'GitHub Container Registry (ghcr.io)'
            - 'Docker Hub (docker.io)'
            - 'Custom Registry (registry.example.com)'
        repository:
          title: Repository Path
          type: string
          description: Repository path in registry (e.g., username/image-name)
          ui:help: 'Example: myorg/my-web-app, username/service-name'
          
    - title: Source Information
      required:
        - sourceProvider
        - sourceRepo
        - sourceBranch
        - dockerfile
        - workflow
      properties:
        sourceProvider:
          title: Source Provider
          type: string
          description: Where your source code is hosted
          enum:
            - github
            - gitlab
          enumNames:
            - 'GitHub'
            - 'GitLab'
          default: github
        sourceRepo:
          title: Source Repository
          type: string
          description: Repository containing the source code (owner/repo)
          ui:help: 'Example: myorg/my-web-app, username/service-repo'
        sourceBranch:
          title: Branch
          type: string
          description: Git branch to monitor for changes
          default: main
        dockerfile:
          title: Dockerfile Path
          type: string
          description: Path to Dockerfile in the repository
          default: Dockerfile
          ui:help: 'Example: Dockerfile, docker/Dockerfile, apps/web/Dockerfile'
        workflow:
          title: Build Workflow
          type: string
          description: GitHub Actions workflow file name that builds this image
          ui:help: 'Example: build.yml, docker-build.yaml, ci.yml'
          
    - title: Rebuild Policy
      properties:
        rebuildDelay:
          title: Rebuild Delay
          type: string
          description: How long to wait after base image updates before triggering rebuilds
          default: 7d
          enum:
            - 1d
            - 3d
            - 7d
            - 14d
            - 30d
          enumNames:
            - '1 day (fast updates)'
            - '3 days (balanced)'
            - '7 days (recommended)'
            - '14 days (conservative)'
            - '30 days (minimal updates)'
        autoRebuild:
          title: Auto-rebuild
          type: boolean
          description: Automatically trigger rebuilds when base images are updated
          default: true
          ui:widget: radio
          ui:options:
            inline: true
          oneOf:
            - const: true
              title: 'Enabled - Automatically rebuild when base images update'
            - const: false
              title: 'Disabled - Manual rebuilds only'
              
    - title: Metadata (Optional)
      properties:
        title:
          title: Display Title
          type: string
          description: Human-readable name for the image
          ui:help: 'Example: My Web Application, User Management Service'
        description:
          title: Description
          type: string
          description: Brief description of what this image contains
          ui:widget: textarea
          ui:options:
            rows: 3
          ui:help: 'Describe the purpose and contents of this container image'
        owner:
          title: Owner
          type: string
          description: Team or person responsible for this image
          ui:help: 'Example: platform-team, backend-team, john.doe'
        system:
          title: System
          type: string
          description: System or product this image belongs to
          default: image-factory
        lifecycle:
          title: Lifecycle
          type: string
          description: Development lifecycle stage
          default: production
          enum:
            - experimental
            - development
            - production
            - deprecated

  steps:
    - id: enroll
      name: Enroll Image in Image Factory
      action: image-factory:enroll
      input:
        name: ${{ parameters.name }}
        registry: ${{ parameters.registry }}
        repository: ${{ parameters.repository }}
        source:
          provider: ${{ parameters.sourceProvider }}
          repo: ${{ parameters.sourceRepo }}
          branch: ${{ parameters.sourceBranch }}
          dockerfile: ${{ parameters.dockerfile }}
          workflow: ${{ parameters.workflow }}
        rebuildPolicy:
          delay: ${{ parameters.rebuildDelay }}
          autoRebuild: ${{ parameters.autoRebuild }}
        metadata:
          title: ${{ parameters.title }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          lifecycle: ${{ parameters.lifecycle }}

  output:
    links:
      - title: View Pull Request
        url: ${{ steps.enroll.output.pullRequestUrl }}
        icon: github
      - title: Source Repository
        url: https://github.com/${{ parameters.sourceRepo }}
        icon: github
      - title: Container Registry
        url: ${{ steps.enroll.output.registryUrl }}
        icon: docker
    text:
      - title: Next Steps
        content: |
          Your image has been successfully enrolled in the Image Factory system!
          
          **What happens next:**
          1. Review and merge the pull request to complete enrollment
          2. The Image Factory will analyze your Dockerfile to discover base image dependencies
          3. Automatic rebuild triggers will be configured based on your policy
          4. Your image will appear as a ManagedImage entity in the Backstage catalog
          
          **Pull Request:** ${{ steps.enroll.output.pullRequestUrl }}