apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@ctoaas.co  # Change this to your email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    # Cloudflare DNS-01 challenge for wildcard certificates
    - dns01:
        cloudflare:
          email: craig@ctoaas.co  # Your Cloudflare email
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
      selector:
        dnsZones:
        - ctoaas.co
