apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: eda-mesh-rabbitmq-secret
spec:
  # Refresh every 5 minutes
  refreshTime: 5m
  
  # Target namespaces with mesh labels
  namespaceSelector:
    matchLabels:
      apim/deps.rabbitmq: "true"
  
  # ExternalSecret template to create in each namespace
  externalSecretSpec:
    secretStoreRef:
      name: eda-mesh-secret-store
      kind: ClusterSecretStore
    
    target:
      name: eda-mesh-rabbit-user
      creationPolicy: Owner
      template:
        metadata:
          labels:
            managed-by: external-secrets
            source: eda-mesh
            secret-type: rabbitmq-user
    
    data:
    - secretKey: username
      remoteRef:
        key: eda-mesh-default-user
        property: username
    
    - secretKey: password
      remoteRef:
        key: eda-mesh-default-user
        property: password