apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kargo-label-secrets
  annotations:
    policies.kyverno.io/title: Add Kargo Labels to Secrets
    policies.kyverno.io/category: Kargo Integration
    policies.kyverno.io/description: Adds Kargo-specific labels to secrets in Kargo project namespaces
spec:
  admission: true
  background: true
  rules:
    - name: label-ghcr-secrets-for-kargo
      match:
        any:
          - resources:
              kinds:
                - Secret
              names:
                - "ghcr-creds"
      preconditions:
        all:
          - key: "{{ request.object.metadata.namespace | ends_with(@, '-kargo') }}"
            operator: Equals
            value: true
          - key: "{{ request.object.type }}"
            operator: Equals
            value: "kubernetes.io/dockerconfigjson"
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              kargo.akuity.io/cred-type: image

    - name: label-git-secrets-for-kargo
      match:
        any:
          - resources:
              kinds:
                - Secret
              names:
                - "github-credentials"
      preconditions:
        all:
          - key: "{{ request.object.metadata.namespace | ends_with(@, '-kargo') }}"
            operator: Equals
            value: true
          - key: "{{ request.object.type }}"
            operator: Equals
            value: "Opaque"
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              kargo.akuity.io/cred-type: git