apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-github-pat-to-backstage
  annotations:
    policies.kyverno.io/title: Sync GitHub PAT to Backstage
    policies.kyverno.io/category: Sync
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: Automatically extracts GitHub PAT from ghcr-creds and creates backstage-github-pat secret
spec:
  rules:
  - name: sync-github-pat-for-backstage
    match:
      any:
      - resources:
          kinds:
          - Namespace
          names:
          - backstage
    context:
    - name: sourceSecret
      apiCall:
        urlPath: /api/v1/namespaces/backstage/secrets/ghcr-creds
        jmesPath: data.".dockerconfigjson" | base64_decode(@) | parse_json(@).auths."ghcr.io"
    generate:
      apiVersion: v1
      kind: Secret
      name: backstage-github-pat
      namespace: backstage
      synchronize: true
      data:
        type: Opaque
        metadata:
          labels:
            managed-by: kyverno
            source: ghcr-creds
        stringData:
          GITHUB_TOKEN: "{{ sourceSecret.password }}"