version: '3'

tasks:
  build:
    desc: Build the UV Docker image
    cmds:
      - docker build -t craigedmunds/uv:local .

  clean:
    desc: Clean up local UV images
    cmds:
      - docker rmi craigedmunds/uv:local || true

  debug:shell:
    desc: Get a shell in the UV image for debugging (if possible)
    cmds:
      - docker run -it --rm craigedmunds/uv:local /bin/bash

  push:
    desc: Push the UV Docker image to registry
    cmds:
      - docker push craigedmunds/uv:local

  run:
    desc: Run the UV image as a server (default mode)
    cmds:
      - docker run -p 8000:8000 craigedmunds/uv:local

  run:script:
    desc: Run a script in the UV image (usage - task run:script SCRIPT=app.py ARGS="--help")
    cmds:
      - docker run --rm craigedmunds/uv:local {{.SCRIPT}} {{.ARGS}}

  shell:
    desc: Open a python shell inside the image
    cmds:
      - docker run -it --rm craigedmunds/uv:local python

  test:analysis:
    desc: Test running the image factory analysis tool
    cmds:
      - docker run --rm craigedmunds/uv:local python -c "print('Analysis tool test')"

  test:entrypoint:
    desc: Test the entrypoint script directly
    cmds:
      - docker run --rm craigedmunds/uv:local --help

  test:kubernetes:
    desc: Test the image in a Kubernetes job (similar to AnalysisTemplate)
    cmds:
      - kubectl run uv-test --image=craigedmunds/uv:local --rm -i --tty --restart=Never -- python --version

  test:paths:
    desc: Test what Python paths are available in the image
    cmds:
      - docker run --rm craigedmunds/uv:local python -c "import sys; print('\n'.join(sys.path))"

  test:simple:
    desc: Test the UV image with a simple script
    cmds:
      - docker run --rm craigedmunds/uv:local python -c "print('Hello from UV image')"