apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: ghcr.io-craigedmunds-backstage
  namespace: image-factory-kargo
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/craigedmunds/backstage
        semverConstraint: ">=0.6.0"
        discoveryLimit: 10
