# Example ManagedImage entities for the Image Factory
# These represent container images we build and maintain

apiVersion: image-factory.io/v1alpha1
kind: ManagedImage
metadata:
  name: backstage
  title: Backstage
  description: Backstage developer portal backend image
  annotations:
    image-factory.io/registry: ghcr.io
    image-factory.io/repository: craigedmunds/backstage
    image-factory.io/digest: sha256:abc123def456
    image-factory.io/last-built: "2024-12-09T10:00:00Z"
    image-factory.io/rebuild-status: up-to-date
    github.com/project-slug: craigedmunds/argocd-eda
  links:
    - url: https://github.com/craigedmunds/argocd-eda/pkgs/container/backstage
      title: GitHub Container Registry
      icon: dashboard
spec:
  type: managed-image
  lifecycle: production
  owner: platform-team
  system: backstage
  source:
    provider: github
    repo: craigedmunds/argocd-eda
    branch: main
    dockerfile: apps/backstage/packages/backend/Dockerfile
    workflow: backstage.yml
  rebuildPolicy:
    delay: 7d
    autoRebuild: true
  dependsOn:
    - resource: node-22-bookworm-slim
      type: base-image

---
apiVersion: image-factory.io/v1alpha1
kind: ManagedImage
metadata:
  name: uv
  title: UV Python Package Manager
  description: UV-based Python application container image
  annotations:
    image-factory.io/registry: ghcr.io
    image-factory.io/repository: craigedmunds/uv
    image-factory.io/digest: sha256:def456abc789
    image-factory.io/last-built: "2024-12-09T09:30:00Z"
    image-factory.io/rebuild-status: up-to-date
    github.com/project-slug: craigedmunds/argocd-eda
  links:
    - url: https://github.com/craigedmunds/argocd-eda/pkgs/container/uv
      title: GitHub Container Registry
      icon: dashboard
spec:
  type: managed-image
  lifecycle: production
  owner: platform-team
  system: image-factory
  source:
    provider: github
    repo: craigedmunds/argocd-eda
    branch: main
    dockerfile: apps/uv/Dockerfile
    workflow: uv.yml
  rebuildPolicy:
    delay: 7d
    autoRebuild: true
  dependsOn:
    - resource: python-3-12-slim
      type: base-image

---
# Example BaseImage entities for the Image Factory
# These represent upstream container images that our managed images depend on

apiVersion: image-factory.io/v1alpha1
kind: BaseImage
metadata:
  name: node-22-bookworm-slim
  title: Node 22 Bookworm Slim
  description: Official Node.js 22 base image (Debian Bookworm slim variant)
  annotations:
    image-factory.io/registry: docker.io
    image-factory.io/repository: library/node
    image-factory.io/tag: 22-bookworm-slim
    image-factory.io/digest: sha256:fedcba987654
    image-factory.io/last-updated: "2024-12-08T15:30:00Z"
spec:
  type: base-image
  lifecycle: production
  owner: upstream
  system: image-factory
  upstream:
    registry: docker.io
    repository: library/node
    tag: 22-bookworm-slim
  dependents:
    - resource: backstage
      type: managed-image

---
apiVersion: image-factory.io/v1alpha1
kind: BaseImage
metadata:
  name: python-3-12-slim
  title: Python 3.12 Slim
  description: Official Python 3.12 base image (slim variant)
  annotations:
    image-factory.io/registry: docker.io
    image-factory.io/repository: library/python
    image-factory.io/tag: 3.12-slim
    image-factory.io/digest: sha256:123456789abc
    image-factory.io/last-updated: "2024-12-07T12:00:00Z"
spec:
  type: base-image
  lifecycle: production
  owner: upstream
  system: image-factory
  upstream:
    registry: docker.io
    repository: library/python
    tag: 3.12-slim
  dependents:
    - resource: uv
      type: managed-image

---
apiVersion: image-factory.io/v1alpha1
kind: BaseImage
metadata:
  name: alpine-3-19
  title: Alpine Linux 3.19
  description: Alpine Linux 3.19 minimal base image
  annotations:
    image-factory.io/registry: docker.io
    image-factory.io/repository: library/alpine
    image-factory.io/tag: "3.19"
    image-factory.io/digest: sha256:987654321fed
    image-factory.io/last-updated: "2024-12-06T08:00:00Z"
spec:
  type: base-image
  lifecycle: production
  owner: upstream
  system: image-factory
  upstream:
    registry: docker.io
    repository: library/alpine
    tag: "3.19"
