apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: github-docker-registry
spec:
  # Refresh every 5 minutes
  refreshTime: 5m
  
  # Target namespaces with this label
  namespaceSelector:
    matchLabels:
      secrets/gh-docker-registry: "true"
  
  # ExternalSecret template to create in each namespace
  externalSecretSpec:
    secretStoreRef:
      name: central-secret-store
      kind: ClusterSecretStore
    
    target:
      name: gh-docker-registry-creds
      creationPolicy: Owner
      template:
        metadata:
          labels:
            managed-by: external-secrets
            source: central-secret-store
            secret-type: gh-docker-registry
            kargo.akuity.io/cred-type: image
        data:
          username: "{{ .username }}"
          password: "{{ .token }}"
          repoURL: "ghcr.io/craigedmunds/backstage"
    
    data:
    - secretKey: username
      remoteRef:
        key: github-pat
        property: username
    
    - secretKey: token
      remoteRef:
        key: github-pat
        property: token