apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: github-git-credentials
spec:
  # Refresh every 5 minutes
  refreshTime: 5m
  
  # Target namespaces with this label
  namespaceSelector:
    matchLabels:
      secrets/gh-git-credentials: "true"
  
  # ExternalSecret template to create in each namespace
  externalSecretSpec:
    secretStoreRef:
      name: central-secret-store
      kind: ClusterSecretStore
    
    target:
      name: github-git-creds
      creationPolicy: Owner
      template:
        metadata:
          labels:
            managed-by: external-secrets
            source: central-secret-store
            secret-type: gh-git-credentials
            kargo.akuity.io/cred-type: git
        data:
          username: "{{ .username }}"
          password: "{{ .token }}"
          repoURL: "https://github.com/craigedmunds/argocd-eda.git"
    
    data:
    - secretKey: username
      remoteRef:
        key: github-pat
        property: username
    
    - secretKey: token
      remoteRef:
        key: github-pat
        property: token