apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: kargo-specific-docker-registry
spec:
  # Refresh every 5 minutes
  refreshTime: 5m
  
  # Target Kargo namespaces (ending with -kargo)
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values: ["backstage-kargo", "image-factory-kargo"]
  
  # ExternalSecret template to create in each namespace
  externalSecretSpec:
    secretStoreRef:
      name: central-secret-store
      kind: ClusterSecretStore
    
    target:
      name: kargo-docker-registry-creds
      creationPolicy: Owner
      template:
        type: Opaque
        metadata:
          labels:
            managed-by: external-secrets
            source: central-secret-store
            secret-type: kargo-docker-registry
            kargo.akuity.io/cred-type: image
        data:
          username: "{{ .username }}"
          password: "{{ .token }}"
          repoURL: "ghcr.io/craigedmunds/*"
          repoURLIsRegex: "true"
    
    data:
    - secretKey: username
      remoteRef:
        key: github-pat
        property: username
    
    - secretKey: token
      remoteRef:
        key: github-pat
        property: token