apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: kargo-admin-credentials
spec:
  # Refresh every 5 minutes
  refreshTime: 5m
  
  # Target namespaces with this label
  namespaceSelector:
    matchLabels:
      secrets/kargo-admin-credentials: "true"
  
  # ExternalSecret template to create in each namespace
  externalSecretSpec:
    secretStoreRef:
      name: central-secret-store
      kind: ClusterSecretStore
    
    target:
      name: kargo-admin-credentials
      creationPolicy: Owner
      template:
        metadata:
          labels:
            managed-by: external-secrets
            source: central-secret-store
            secret-type: kargo-admin-credentials
    
    data:
    - secretKey: ADMIN_ACCOUNT_PASSWORD_HASH
      remoteRef:
        key: kargo-admin-credentials
        property: passwordHash
    
    - secretKey: ADMIN_ACCOUNT_TOKEN_SIGNING_KEY
      remoteRef:
        key: kargo-admin-credentials
        property: tokenSigningKey