version: '3'

tasks:
  test:unit:setup:
    desc: "Set up Image Factory development environment"
    cmds:
      - task: app:setup
      - task: cdk8s:setup

  test:unit:
    desc: "Run unit tests for Image Factory"
    cmds:
      - task: app:test:unit
      - task: cdk8s:test:unit

  # Component-specific setup tasks
  test:integration:setup:
    desc: "Set up integration test"
    dir: tests/integration
    cmds:
      - cmd: echo "🔧 Setting up integration test environment..."
        silent: true
      - cmd: |
          if [ -n "$CI" ]; then
            echo "CI environment detected, skipping virtual environment creation"
          else
            if [ ! -d ".venv" ]; then
              echo "Creating virtual environment..."
              python3 -m venv .venv
            fi
          fi
        silent: true
      - cmd: |
          echo "Installing dependencies..."
          if [ -n "$CI" ]; then
            pip install -e ".[dev]"
          else
            .venv/bin/pip install -e ".[dev]"
          fi
        silent: true

  test:integration:
    desc: "Run integration tests for Image Factory"
    dir: tests/integration
    cmds:
      - cmd: |
          if [ -n "$CI" ]; then
            python -m pytest test_integration.py -v
          else
            .venv/bin/python -m pytest test_integration.py -v
          fi
      
  test:acceptance:
    desc: "Run acceptance tests for Image Factory"
    dir: .
    cmds:
      - cmd: echo "🧪 Running Kargo acceptance tests..."
        silent: true
      - npm install
      - npm run test:kargo

  test:all:
    desc: "Run all tests for Image Factory"
    deps: [test:unit, test:integration, test:acceptance]

  # Component-specific setup tasks
  app:setup:
    desc: "Set up Image Factory app component"
    dir: app
    cmds:
      - cmd: echo "🔧 Setting up Image Factory app environment..."
        silent: true
      - cmd: |
          if [ -n "$CI" ]; then
            echo "CI environment detected, skipping virtual environment creation"
          else
            if [ ! -d ".venv" ]; then
              echo "Creating virtual environment..."
              python3 -m venv .venv
            fi
          fi
        silent: true
      - cmd: |
          echo "Installing dependencies..."
          if [ -n "$CI" ]; then
            pip install -e ".[dev]"
          else
            .venv/bin/pip install -e ".[dev]"
          fi
        silent: true

  cdk8s:setup:
    desc: "Set up Image Factory CDK8s component"
    dir: cdk8s
    cmds:
      - cmd: echo "🔧 Setting up Image Factory CDK8s environment..."
        silent: true
      - cmd: |
          if [ -n "$CI" ]; then
            echo "CI environment detected, skipping virtual environment creation"
          else
            if [ ! -d ".venv" ]; then
              echo "Creating virtual environment..."
              
              echo "Finding compatible Python version (>=3.10, <3.15)"
              python_cmd=""
              for py in python3.11 python3.12 python3.13 python3.10 python3; do
                if command -v "$py" >/dev/null 2>&1; then
                  if $py -c "import sys; exit(0 if (3, 10) <= sys.version_info[:2] < (3, 15) else 1)" 2>/dev/null; then
                    python_version=$($py -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
                    echo "Found compatible Python $python_version ($py)"
                    python_cmd="$py"
                    break
                  fi
                fi
              done
              
              if [ -z "$python_cmd" ]; then
                echo "Error: No compatible Python version found"
                echo "Required: Python >=3.10, <3.15 (GitHub Actions uses 3.11)"
                echo "Available Python versions:"
                for py in python3.11 python3.12 python3.13 python3.10 python3; do
                  if command -v "$py" >/dev/null 2>&1; then
                    version=$($py -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>/dev/null || echo "unknown")
                    echo "  $py: Python $version"
                  fi
                done
                exit 1
              fi
              
              $python_cmd -m venv .venv
            fi
          fi
        silent: true
      - cmd: |
          echo "Installing dependencies..."
          if [ -n "$CI" ]; then
            pip install -e ".[dev]"
          else
            .venv/bin/pip install -e ".[dev]"
          fi
        silent: true

  # Component-specific test tasks
  app:test:unit:
    desc: "Run unit tests for Image Factory app component"
    dir: app
    cmds:
      - cmd: echo "🧪 Running Image Factory app unit tests..."
        silent: true
      - cmd: |
          if [ -n "$CI" ]; then
            python -m pytest tests/test_app.py -v
          else
            .venv/bin/python -m pytest tests/test_app.py -v
          fi

  cdk8s:test:unit:
    desc: "Run unit tests for Image Factory CDK8s component"
    dir: cdk8s
    cmds:
      - cmd: echo "🧪 Running Image Factory CDK8s unit tests..."
        silent: true
      - cmd: |
          if [ -n "$CI" ]; then
            python -m pytest test_main.py -v
          else
            .venv/bin/python -m pytest test_main.py -v
          fi
      
  cdk8s:synth:
    desc: Synthesize CDK8s manifests
    dir: cdk8s
    cmds:
      - cmd: |
          if [ -n "$CI" ]; then
            python main.py
          else
            .venv/bin/python main.py
          fi
      
  cdk8s:deploy:
    desc: Deploy CDK8s manifests to cluster
    dir: cdk8s
    deps:
      - cdk8s:synth
    cmds:
      - kubectl apply -f dist/image-factory.k8s.yaml
      
  tool:run:
    desc: Run the image factory analysis tool
    dir: app
    cmds:
      - cmd: |
          if [ -n "$CI" ]; then
            python app.py --image-factory-dir ../
          else
            .venv/bin/python app.py --image-factory-dir ../
          fi

  tool:run:uv:
    desc: Run analysis tool for UV image (local testing)
    dir: app
    cmds:
      - cmd: |
          if [ -n "$CI" ]; then
            python app.py \
              --image uv \
              --tag "local-test" \
              --digest "sha256:local-test" \
              --dockerfile "apps/uv/Dockerfile" \
              --source-repo "craigedmunds/argocd-eda" \
              --source-provider "github" \
              --git-repo "https://github.com/craigedmunds/argocd-eda.git" \
              --git-branch "main" \
              --image-factory-dir ../
          else
            .venv/bin/python app.py \
              --image uv \
              --tag "local-test" \
              --digest "sha256:local-test" \
              --dockerfile "apps/uv/Dockerfile" \
              --source-repo "craigedmunds/argocd-eda" \
              --source-provider "github" \
              --git-repo "https://github.com/craigedmunds/argocd-eda.git" \
              --git-branch "main" \
              --image-factory-dir ../
          fi

  tool:run:backstage:
    desc: Run analysis tool for Backstage image (local testing)
    dir: app
    cmds:
      - cmd: |
          if [ -n "$CI" ]; then
            python app.py \
              --image backstage \
              --tag "local-test" \
              --digest "sha256:local-test" \
              --dockerfile "backstage/app/packages/backend/Dockerfile" \
              --source-repo "craigedmunds/argocd-eda" \
              --source-provider "github" \
              --git-repo "https://github.com/craigedmunds/argocd-eda.git" \
              --git-branch "main" \
              --image-factory-dir ../
          else
            .venv/bin/python app.py \
              --image backstage \
              --tag "local-test" \
              --digest "sha256:local-test" \
              --dockerfile "backstage/app/packages/backend/Dockerfile" \
              --source-repo "craigedmunds/argocd-eda" \
              --source-provider "github" \
              --git-repo "https://github.com/craigedmunds/argocd-eda.git" \
              --git-branch "main" \
              --image-factory-dir ../
          fi

  # Diagnostic and Status Tasks
  status:
    desc: Show comprehensive status of Image Factory components
    cmds:
      - echo "=== Image Factory Status Overview ==="
      - echo ""
      - echo "📋 Kargo Project Status:"
      - kubectl get project image-factory-kargo -n image-factory-kargo -o wide || echo "❌ Project not found"
      - echo ""
      - echo "🏭 Warehouses Status:"
      - kubectl get warehouses -n image-factory-kargo -o wide || echo "❌ No warehouses found"
      - echo ""
      - echo "🎭 Stages Status:"
      - kubectl get stages -n image-factory-kargo -o wide || echo "❌ No stages found"
      - echo ""
      - echo "📦 Freight Status:"
      - kubectl get freight -n image-factory-kargo -o wide || echo "❌ No freight found"
      - echo ""
      - echo "🚀 Promotions Status (last 10):"
      - kubectl get promotions -n image-factory-kargo --sort-by=.metadata.creationTimestamp -o wide | tail -11 || echo "❌ No promotions found"
      - echo ""
      - echo "🔬 AnalysisRuns Status:"
      - kubectl get analysisruns -n image-factory-kargo -o wide || echo "❌ No analysis runs found"
      - echo ""
      - echo "⚙️ Jobs Status:"
      - kubectl get jobs -n image-factory-kargo -o wide || echo "❌ No jobs found"
      - echo ""
      - echo "🐳 Pods Status:"
      - kubectl get pods -n image-factory-kargo -o wide || echo "❌ No pods found"

  logs:
    desc: Show logs from all running Image Factory components
    cmds:
      - echo "=== Image Factory Logs ==="
      - echo ""
      - echo "📋 Recent Events:"
      - kubectl get events -n image-factory-kargo --sort-by='.lastTimestamp' | tail -20 || echo "❌ No events found"
      - echo ""
      - echo "⚙️ Job Logs (if any running):"
      - kubectl get jobs -n image-factory-kargo -o name | xargs -I {} kubectl logs -n image-factory-kargo {} --tail=50 || echo "❌ No jobs found"
      - echo ""
      - echo "🐳 Pod Logs (if any running):"
      - kubectl get pods -n image-factory-kargo --field-selector=status.phase=Running -o name | xargs -I {} kubectl logs -n image-factory-kargo {} --tail=50 || echo "❌ No running pods found"

  logs:analysis:
    desc: Show logs from the most recent AnalysisRun
    cmds:
      - echo "=== Most Recent AnalysisRun Logs ==="
      - kubectl get analysisruns -n image-factory-kargo --sort-by=.metadata.creationTimestamp -o name | tail -1 | xargs -I {} kubectl describe -n image-factory-kargo {} || echo "❌ No AnalysisRuns found"

  logs:promotion:
    desc: Show logs from the most recent promotion
    cmds:
      - echo "=== Most Recent Promotion Logs ==="
      - kubectl get promotions -n image-factory-kargo --sort-by=.metadata.creationTimestamp -o name | tail -1 | xargs -I {} kubectl describe -n image-factory-kargo {} || echo "❌ No promotions found"

  debug:stage:
    desc: Debug a specific stage
    cmds:
      - echo "=== Stage Debug ==="
      - echo ""
      - echo "📋 Stage Configuration:"
      - kubectl get stage {{.STAGE | default "analyze-dockerfile-uv"}} -n image-factory-kargo -o yaml || echo "❌ Stage not found"
      - echo ""
      - echo "🚀 Recent Promotions for this Stage:"
      - kubectl get promotions -n image-factory-kargo --sort-by=.metadata.creationTimestamp | grep {{.STAGE | default "analyze-dockerfile-uv"}} | tail -5 || echo "❌ No promotions found"
      - echo ""
      - echo "🔬 Recent AnalysisRuns for this Stage:"
      - kubectl get analysisruns -n image-factory-kargo --sort-by=.metadata.creationTimestamp | grep {{.STAGE | default "analyze-dockerfile-uv"}} | tail -5 || echo "❌ No analysis runs found"

  debug:secrets:
    desc: Debug secret configuration and availability
    cmds:
      - echo "=== Secrets Debug ==="
      - echo ""
      - echo "🔐 Available Secrets:"
      - kubectl get secrets -n image-factory-kargo || echo "❌ No secrets found"
      - echo ""
      - echo "🔍 ServiceAccount Configuration:"
      - kubectl get serviceaccount image-factory -n image-factory-kargo -o yaml || echo "❌ ServiceAccount not found"

  clean:failed:
    desc: Clean up failed jobs and pods
    cmds:
      - echo "=== Cleaning Failed Resources ==="
      - echo ""
      - echo "🧹 Deleting failed jobs:"
      - kubectl delete jobs -n image-factory-kargo --field-selector status.successful=0 || echo "❌ No failed jobs to delete"
      - echo ""
      - echo "🧹 Deleting failed pods:"
      - kubectl delete pods -n image-factory-kargo --field-selector status.phase=Failed || echo "❌ No failed pods to delete"

  watch:
    desc: Watch Image Factory resources in real-time
    cmds:
      - echo "=== Watching Image Factory Resources ==="
      - echo "Press Ctrl+C to stop watching"
      - kubectl get promotions,analysisruns,jobs,pods -n image-factory-kargo -w