apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: users
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    cleanup.policy: "compact"
    min.insync.replicas: "1"