apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-taint-remover
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-taint-remover
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-taint-remover
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-taint-remover
subjects:
- kind: ServiceAccount
  name: node-taint-remover
  namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: remove-control-plane-taint
  namespace: kube-system
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: node-taint-remover
      restartPolicy: OnFailure
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: remove-taint
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          echo "Removing control-plane taint from all nodes..."
          kubectl taint nodes --all node-role.kubernetes.io/control-plane:NoSchedule- || true
          echo "Taint removal complete"
          kubectl get nodes -o custom-columns=NAME:.metadata.name,TAINTS:.spec.taints
